
--5) RANKING DAS CINCO CATEGRORIAS COM MAIS VENDAS AGRUPADAS POR ANO

WITH RESULT AS 
(SELECT C.CATEGORY_NAME                             CATEG,             
	   DATE_PART('YEAR', O.ORDER_DATE)              ANO,
	   SUM(ROUND((OD.UNIT_PRICE * OD.QUANTITY),2))  TOTAL,
	   ROW_NUMBER() OVER (PARTITION BY ANO ORDER BY ANO, TOTAL DESC) AS RES 
FROM CATEGORIES C 
INNER JOIN PRODUCTS      P  ON (P.CATEGORY_ID = C.CATEGORY_ID)
INNER JOIN ORDER_DETAILS OD ON (OD.PRODUCT_ID = P.PRODUCT_ID)
INNER JOIN ORDERS        O  ON (O.ORDER_ID = OD.ORDER_ID)
GROUP BY CATEG, ANO
ORDER BY ANO, TOTAL DESC
LIMIT 100
),
FILTRO AS (
  SELECT CATEG, ANO, TOTAL FROM RESULT WHERE RES <=5
)
  SELECT CATEG, ANO, TOTAL FROM FILTRO