-- 1) PRODUTOS VENDIDOS ABAIXO DO PREÇO DE TABELA

-- Por Venda
SELECT O.ORDER_ID      ID_VENDA,
       P.PRODUCT_ID    ID_PROD,
       P.PRODUCT_NAME  PRODUTO,
       O.QUANTITY      QUANTIDADE,
       O.UNIT_PRICE    PRECO_VENDA,
       P.UNIT_PRICE    PRECO_TABELA
FROM ORDER_DETAILS O,  PRODUCTS P 
WHERE O.PRODUCT_ID = P.PRODUCT_ID 
  AND PRECO_VENDA  < PRECO_TABELA
ORDER BY PRECO_VENDA DESC;

-- AGRUPADO POR PRODUTO
SELECT COUNT(O.ORDER_ID)           TOTAL_VENDAS,
        P.PRODUCT_ID               ID_PROD,
        P.PRODUCT_NAME             PRODUTO,
       SUM(O.QUANTITY)             QTD_TOTAL,
       ROUND(SUM(O.UNIT_PRICE),2)  PRECO_VENDA,
       ROUND(SUM(P.UNIT_PRICE),2)  PRECO_TABELA,
       ROUND(SUM(P.UNIT_PRICE - O.UNIT_PRICE),2) DIFERENCA
FROM ORDER_DETAILS O, PRODUCTS P 
WHERE O.PRODUCT_ID = P.PRODUCT_ID 
AND  (O.UNIT_PRICE < P.UNIT_PRICE)
GROUP BY P.PRODUCT_ID,
         P.PRODUCT_NAME
ORDER BY PRECO_VENDA DESC;