-- 2) VENDEDORES QUE MAIS VENDERAM EM 2022

SELECT  E.FIRST_NAME || ' ' || E.LAST_NAME                  as NOME, 
    ROUND(SUM(OD.UNIT_PRICE * OD.QUANTITY - OD.DISCOUNT),2) as TOTAL 
FROM ORDER_DETAILS OD
INNER JOIN ORDERS    O ON O.ORDER_ID  = OD.ORDER_ID
INNER JOIN EMPLOYEES E ON E.EMPLOYEE_ID = O.EMPLOYEE_ID
WHERE DATE_PART('YEAR', O.ORDER_DATE) = 2022
GROUP BY NOME
ORDER BY TOTAL DESC;