-- 4) DIFERENCA DAS VENDAS DE PRODUTOS ENTRE O ANO ATUAL E O ANTERIOR MOSTRANDO POR FORNECEDOR

SELECT A2020.SUPPLIER_ID,
       A2020.COMPANY_NAME,
	   A2020.TOTAL A2020,
	   A2021.TOTAL A2021, 
      (A2021.TOTAL - A2020.TOTAL) TOTAL
FROM 
	(SELECT S.SUPPLIER_ID, 
	        S.COMPANY_NAME, 
	        SUM(ROUND((OD.UNIT_PRICE * OD.QUANTITY),2)) TOTAL
    FROM ORDER_DETAILS OD
	INNER JOIN ORDERS    O ON (O.ORDER_ID    = OD.ORDER_ID)
	INNER JOIN PRODUCTS  P ON (P.PRODUCT_ID  = OD.PRODUCT_ID )
	INNER JOIN SUPPLIERS S ON (S.SUPPLIER_ID = P.SUPPLIER_ID )
	WHERE DATE_PART('YEAR', O.ORDER_DATE) = 2020
	GROUP BY S.SUPPLIER_ID,S.COMPANY_NAME
	ORDER BY S.SUPPLIER_ID) A2020,

	(SELECT S.SUPPLIER_ID, 
	        S.COMPANY_NAME, 
	        SUM(ROUND((OD.UNIT_PRICE * OD.QUANTITY),2)) TOTAL
    FROM ORDER_DETAILS OD
	INNER JOIN ORDERS    O ON (O.ORDER_ID    = OD.ORDER_ID)
	INNER JOIN PRODUCTS  P ON (P.PRODUCT_ID  = OD.PRODUCT_ID )
	INNER JOIN SUPPLIERS S ON (S.SUPPLIER_ID = P.SUPPLIER_ID )
	WHERE DATE_PART('YEAR', O.ORDER_DATE) = 2021
	GROUP BY S.SUPPLIER_ID,S.COMPANY_NAME
	ORDER BY S.SUPPLIER_ID) A2021

WHERE (A2020.SUPPLIER_ID = A2021.SUPPLIER_ID)
GROUP BY A2020.SUPPLIER_ID,
         A2021.SUPPLIER_ID,
         A2020.COMPANY_NAME,
		 A2021.COMPANY_NAME,
		 A2020.TOTAL,
		 A2021.TOTAL